### ISSUE TITLE
Unarr's license should be LGPL3+

### ISSUE THREAD

**Issue by selmf** [OpenMandrivaAssociation/unarr#1]
Unarr's License isn't LGPL2+, it is LGPL3+. See [https://github.com/zeniko/unarr/blob/master/COPYING](https://github.com/zeniko/unarr/blob/master/COPYING).

This is an error that you've inherited when adapting my experimental OpenSuse/Fedora specfile from OBS. Kudos to everyone that helped adapting this mess of a specfile for real world usage. I never quite finished my experiments so I was very surprised someone actually dug that stuff out and found it usefull :+1:

**Comment by tpgxyz** [comment]
Thanks, fixed.

https://github.com/OpenMandrivaAssociation/unarr/commit/d723f42b4ef39b7961ada271125461261184934e
